mycat:
    build: mycat
    restart: always
    container_name: mycat
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./conf/:/mycat/conf/:ro
        - ./logs/:/mycat/logs/:rw
    ports:
        - "8066:8066"
        - "9066:9066"
    ulimits:
        nproc: 65535
    hostname: mycat
    mem_limit: 1024m
