version: '3.0'
services:
 redis:
    restart: always
    image: redis:4
    container_name: redis
    privileged: true
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - ./data:/data
        #- ./redis.conf:/usr/local/etc/redis/redis.conf
    network_mode: "host"
    ports:
        - "6379:6379"
    command:
       #redis-server /usr/local/etc/redis/redis.conf
       --requirepass "jumpserver"
       #--appendonly yes
    logging:
        driver: "json-file"
        options:
           max-size: "10M"
           max-file: "5"
       
