version: '3.2'
services:
  jenkins:
    restart: always
    image: jenkins/jenkins:2.387.3-jdk11
    container_name: jenkins1
    hostname: jenkins1
    environment:
        - JENKINS_OPTS="--prefix=/jenkins"
        - JAVA_OPTS="-Duser.timezone=Asia/Shanghai -Difile.encoding=utf-8 -Xms512m -Xmx512m"
        # - DOCKER_HOST=tcp://192.168.10.3:2375
    volumes:
        - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro"
        - ./jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
    #ports:
    #    - "8085:8080"
    networks:
        default:
    extra_hosts:
        - 'demo.com:10.20.33.152'     

networks:
  default:
    external:
      name: network

