version: '3'
services:
  portainer:
    image: portainer/portainer-ce:2.16.2
    container_name: portainer
    restart: always
    networks:
        portainer:
    ports:
      #- 9010:9000
      - 9443:9443
    environment:
      AGENT_SECRET: NGFiYTQzYjItNzY1ZC00Njk1     # agent认证 
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_aliyun:/data

networks:
  portainer:
    external:
      name: network

