apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-efk-elasticsearch-0
    namespace: efk
  nfs:
    path: /home/data/db/k8s_pv/es-data
    server: 192.168.31.120
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
