apiVersion: v1
kind: Namespace
metadata:
  name: logstash
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-logstash
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-logstash-0
    namespace: logstash
  nfs:
    path: /home/data/db/k8s_pv/data-logstash
    server: 192.168.31.120
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-logstash-0
  namespace: logstash
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv-data-logstash

