version: '3.0'
services:
 kafka-manager:
    restart: always
    image: sheepkiller/kafka-manager:stable
    container_name: kafka_manager
    #privileged: true
    volumes:
        - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    ports:
        - "9000:9000"
    environment:
        - ZK_HOSTS=zookeeper:2181
        - APPLICATION_SECRET=letmein
    #network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
 zookeeper:
    restart: always
    image: zookeeper
    container_name: zookeeper
    #privileged: true
    environment:
        - TZ=Asia/Shanghai
    volumes:
        - ./data:/data
    ports:
        - "2181:2181"
    logging:
        driver: "json-file"
        options:
            max-size: "10M"