mysql:
    restart: always
    image: mysql
    container_name: mysql_master
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
        - ./data/:/var/lib/mysql
        - ./my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    privileged: true
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=mysql
        #- MYSQL_USER=admin 
        #- MYSQL_PASSWORD=admin
        - TZ=Asia/Shanghai
    command:
         --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
