version: '3'

services:
  pritunl:
    image: 'pritunl:latest'
    restart: always
    container_name: pritunl_server
    #privileged: true
    environment:
      - APP.REDIRECT_SERVER=false   #关闭80端口，配置数据库后手动设置才生效
      - APP.SERVER_PORT=443         #设置web端口
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./pritunl_data:/var/lib/pritunl
      - ./pritunl.conf:/etc/pritunl.conf
    #network_mode: "host"
    networks:
        mongo:
    ports:
      - '1443:443'
      - '1194:1194/udp'
      - '1194:1194/tcp'

  mongo:
    image: mongo:4.2
    restart: always
    container_name: pritunl_mongo_auth
    #privileged: true
    environment:
        - TZ=Asia/Shanghai
        - MONGO_INITDB_ROOT_USERNAME=dbadmin
        - MONGO_INITDB_ROOT_PASSWORD=dbadminpasswd
        #- MONGO_INITDB_DATABASE=pritunl
    volumes:
        - /etc/localtime:/etc/localtime:ro
        #- ./mongod.conf:/etc/mongod.conf.orig
        - ./db:/data/db
        #- ./logs:/var/log/mongodb
    networks:
        mongo:
    ports:
        - "27017:27017"
    #command: --storageEngine wiredTiger

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    depends_on:
      - mongo
    environment:
      - TZ=Asia/Shanghai
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dbadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dbadminpasswd
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
        mongo:
    ports:
      - 8081:8081

networks:
    mongo:
       driver: bridge

