version: '3'
services:
  zookeeper_01:
    image: zookeeper
    container_name: zookeeper_01
    restart: always
    ports:
      - "2181:2181"
      - "2888"
      - "3888"
    volumes:
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper_01:2888:3888 server.2=zookeeper_02:2888:3888 server.3=zookeeper_03:2888:3888
  
  zookeeper_02:
    image: zookeeper
    container_name: zookeeper_02
    restart: always
    ports:
      - "2182:2181"
      - "2888"
      - "3888"
    volumes:
      - ./zoo2/data:/data
      - ./zoo2/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper_01:2888:3888 server.2=zookeeper_02:2888:3888 server.3=zookeeper_03:2888:3888
  
  zookeeper_03:
    image: zookeeper
    container_name: zookeeper_03
    restart: always
    ports:
      - "2183:2181"
      - "2888"
      - "3888"
    volumes:
      - ./zoo3/data:/data
      - ./zoo3/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper_01:2888:3888 server.2=zookeeper_02:2888:3888 server.3=zookeeper_03:2888:3888
