version: '3'
services:
  skywalking-es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    container_name: skywalking-es
    ports:
      - 9200:9200
      - 9300:9300
    networks:
       default:
    environment:
      TZ: Asia/Shanghai
      discovery.type: single-node
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
  oap:
    restart: always
    image: apache/skywalking-oap-server:6.2.0
    container_name: oap
    depends_on:
      - skywalking-es
    #network_mode: "host"
    ports:
      - 11800:11800
      - 12800:12800
      - 1234:1234
    networks:
      default:
    environment:
      TZ: Asia/Shanghai
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: skywalking-es:9200
      SW_STORAGE_ES_INDEX_SHARDS_NUMBER: 1
      #SW_CORE_GRPC_HOST: 
    #volumes:
    #  - ./application.yml:/skywalking/config/application.yml
    
  ui:
    restart: always
    image: apache/skywalking-ui:6.2.0
    container_name: ui
    depends_on:
      - oap
    ports:
      - 10004:8080
    networks:
        default:
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: oap:12800

#  skywalking-kibana:
#    image: docker.elastic.co/kibana/kibana:6.8.1
#    container_name: skywalking-kibana
#    environment:
#      TZ: Asia/Shanghai
#      SERVER_NAME: kibana
#      ELASTICSEARCH_HOSTS: http://skywalking-es:9200
#    ports:
#      - 5602:5601
#    networks:
#        default:

networks:
  default:
    external:
      name: oap-network
