apiVersion: v1
kind: Namespace
metadata:
  name: kong
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kong-pgsql
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-postgres-0
    namespace: kong
  nfs:
    path: /home/data/db/k8s_pv/kong-pgsql
    server: 192.168.31.120
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
