version: '2.0'
services:
  #db:
  #  image: mariadb:10.4
  #  container_name: seafile-mysql
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=seafile  # Requested, set the root's password of MySQL service.
  #    - MYSQL_LOG_CONSOLE=true
  #  volumes:
  #    - ./seafile-mysql:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
  #  ports:
  #      - "3307:3306"
  #  networks:
  #    - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    #    ports:
    #  - "84:80"
    # - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - ./seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
      - ./ceph:/etc/ceph   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=mysql
      - DB_ROOT_PASSWD=mysql  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=Asia/Shanghai # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=admin@demo.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=admin     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether use letsencrypt to generate cert.
      - SEAFILE_SERVER_HOSTNAME=seafile.demo.com # Specifies your host name.
    depends_on:
      #- db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:
    external:
      name: network
