##官方镜像https://hub.docker.com/u/zabbix/
## songliang
## 2018.5.1

version: '3.1'

networks:
  zabbix:

services:
 zabbix_web_nginx:
    restart: always
    image: zabbix/zabbix-web-nginx-mysql:centos-latest
    container_name: zabbix_web_nginx
    privileged: true
    hostname: zabbix_web_nginx
    volumes:
        - ./ttf/DejaVuSans.ttf:/usr/share/fonts/ttf-dejavu/DejaVuSans.ttf
    links:
        - zabbix_mysql
        - zabbix_server
    ports:
        - "80:80"
    environment:
        - DB_SERVER_HOST=zabbix_mysql
        - DB_SERVER_PORT=3306
        - MYSQL_USER=zabbix
        - MYSQL_PASSWORD=zabbix
        - ZBX_SERVER_HOST=zabbix_server
        - PHP_TZ=Asia/Shanghai
    networks:
        - zabbix
    
 zabbix_server:
    restart: always
    image: zabbix/zabbix-server-mysql:centos-latest
    container_name: zabbix_server
    privileged: true
    hostname: zabbix_server
    volumes:
        - /etc/localtime:/etc/localtime:ro
        #- ./script/mail.sh:/usr/lib/zabbix/alertscripts/mail.sh
    links:
        - zabbix_mysql
        - zabbix_agent
    ports:
        - "15051:10051"
    environment:
        - DB_SERVER_HOST=zabbix_mysql
        - DB_SERVER_PORT=3306
        - MYSQL_USER=zabbix
        - MYSQL_PASSWORD=zabbix
    networks:
        - zabbix

 zabbix_mysql:
    restart: always
    image: mysql
    container_name: zabbix_mysql
    privileged: true
    hostname: zabbix_mysql
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./data:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        #- MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_DATABASE=zabbix
        - MYSQL_USER=zabbix
        - MYSQL_PASSWORD=zabbix
        - TZ=Asia/Shanghai
    networks:
        - zabbix
    command:
         --character-set-server=utf8 --collation-server=utf8_general_ci
              
 zabbix_agent:
    restart: always
    image: zabbix/zabbix-agent:centos-latest
    container_name: zabbix_agent
    privileged: true
    hostname: zabbix_agent
    #volumes:
        #- ./ttf/DejaVuSans.ttf:/usr/share/fonts/ttf-dejavu/DejaVuSans.ttf   
    #links:
    #    - zabbix_server
    #ports:
    #    - "10050:10050"
    environment:
        - ZBX_HOSTNAME=Zabbix server
        - ZBX_SERVER_HOST=zabbix_server
    networks:
        - zabbix

