version: '3'

services:
  hfish:
    image: imdevops/hfish:latest
    container_name: hfish
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - USERNAME=admin
      - PASSWORD=admin
    volumes:
      - ./data:/opt
    networks:
        hfish-net:
    ports:
      - 21:21
      - 22:22
      - 23:23
      - 3306:3306
      - 6379:6379
      - 8080:8080
      - 8989:8989
      - 9000:9000
      - 9001:9001
      - 11211:11211
      - 69:69
      - 5900:5900
      - 8081:8081
      - 9200:9200
      
networks:
  hfish-net:
    external:
      name: public
