version: '3.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "xpack.security.enabled=false"
        #- "xpack.security.transport.ssl.enabled=true"
        #- "xpack.security.transport.ssl.keystore.type=PKCS12"
        #- "xpack.security.transport.ssl.verification_mode=certificate"
        #- "xpack.security.transport.ssl.keystore.path=elastic-stack-ca.p12"
        #- "xpack.security.transport.ssl.truststore.path=elastic-stack-ca.p12"
        #- "xpack.security.transport.ssl.truststore.type=PKCS12"
      - "indices.fielddata.cache.size=20%"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      #- ./elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12
      - ./data02:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
      
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.1
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      #SERVER_BASEPATH: /kibana
      I18N_LOCALE: zh-CN
      ELASTICSEARCH_HOSTS: http://es01:9200
      #ELASTICSEARCH_USERNAME: elastic
      #ELASTICSEARCH_PASSWORD: "demo!@#"
    ports:
      - 5601:5601
    networks:
      - elastic

  filebeat:
    image: "docker.elastic.co/beats/filebeat:8.4.1"
    container_name: filebeat
    #restart: always
    privileged: true
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/fields.yml:/usr/share/filebeat/fields.yml
      - ./filebeat/module:/usr/share/filebeat/module
      - ./filebeat/modules.d:/usr/share/filebeat/modules.d
      #- ./filebeat/inputs.d:/usr/share/filebeat/inputs.d
      #- ./filebeat/logs:/usr/share/filebeat/logs
      #- ./filebeat/data:/usr/share/filebeat/data
      #- ./nginx-log:/var/log/nginx/
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - elastic

networks:
  elastic:
     external:
      name: network

