#
version: '3'

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    image: minio/minio:latest
    container_name: minio1
    restart: always
    volumes:
      - ./minio/data:/data
      #- ./certs:/root/.minio/certs
      #- ./minio1/data1-2:/data2
    #expose:
    ports:
      - "9002:9000"
      - "9091:9091"
    networks:
      default:
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_PROMETHEUS_URL: "http://prometheus:9090/prome/"
    #command: server /data1
    command: server /data --console-address ":9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  default:
    external:
      name: network
