version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    environment: 
      - TZ=Asia/Shanghai
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitor

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    environment: 
      - TZ=Asia/Shanghai
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
      #- ./etc/node_exporter/prom:/node_exporter/prom
    #ports:
    #  - '9100:9100'
    #networks:
    #    - monitor
    network_mode: "host"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      #- '--collector.textfile.directory=/node_exporter/prom'


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - TZ=Asia/Shanghai
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      #- ./grafana/conf:/etc/grafana/
      - ./grafana/data:/var/lib/grafana
      - ./grafana/log:/var/log/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor

networks:
  monitor:
    external:
      name: network
