version: '3.2'
services:
  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    hostname: redis_exporter
    restart: always
    ports:
        - "9121:9121"
    command:
        --redis.addr=redis://192.168.31.120:6379
    networks:
        default:

    logging:
      driver: "json-file"
      options:
        max-size: "5M"

networks:
  default:
    external:
      name: network-public

