zabbix-mysql:
    restart: always
    image: mysql
    container_name: zabbix-mysql
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data/songliang/zabbix/mysql/:/var/lib/mysql
    privileged: true
    ports:
        - "53306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=bZ8xy@x0yhPkbetq
        - MYSQL_USER=zabbix 
        - MYSQL_PASSWORD=k*nuPkna0Ssvaxe1
        - TZ=Asia/Shanghai
    command:
         --character-set-server=utf8 --collation-server=utf8_general_ci
