zabbix-mysql:
    restart: always
    image: mysql
    container_name: zabbix_mysql
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data/mysql/:/var/lib/mysql
    privileged: true
    ports:
        - "53306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=msyql
        - TZ=Asia/Shanghai
    command:
         --character-set-server=utf8 --collation-server=utf8_general_ci
