version: '3'
services:

  mongo:
    image: mongo:4.2
    restart: always
    container_name: mongo_server_auth
    #privileged: true
    environment:
        - TZ=Asia/Shanghai
        - MONGO_INITDB_ROOT_USERNAME=dbadmin
        - MONGO_INITDB_ROOT_PASSWORD=dbadminpasswd
        - MONGO_INITDB_DATABASE=wpd
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./mongod.conf.orig;/etc/mongod.conf.orig
        - ./db:/data/db
        - ./logs:/var/log/mongo
    networks:
        mongo:
    ports:
        - "27017:27017"
    command: --storageEngine wiredTiger

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    environment:
      - TZ=Asia/Shanghai
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dbadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dbadminpasswd
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
        mongo:
    ports:
      - 8081:8081

networks:
    mongo:
       driver: bridge

