version: '3.1'
services:

  mongo:
    image: mongo:3.2
    restart: always
    container_name: mongo_server_auth
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=xrjfMongodb2018
        - MONGO_INITDB_DATABASE=wpd
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - ./mongod.conf.orig;/etc/mongod.conf.orig
        - ./db:/data/db
    privileged: true
    ports:
        - "27017:27017"
    command: --storageEngine wiredTiger

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    ports:
      - 85:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=xrjfMongodb2018



