version: '3.0'
services:
 kafka-manager:
    restart: always
    image: sheepkiller/kafka-manager:stable
    container_name: kafka_manager
    privileged: true
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
        - "9000:9000"
    environment:
        - ZK_HOSTS=192.168.0.200:2181
        - APPLICATION_SECRET=letmein
    #network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
 zookeeper:
    restart: always
    image: zookeeper
    container_name: zookeeper
    privileged: true
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - ./zookeeper/:/tmp/zookeeper
    ports:
        - "2181:2181"
